### ISSUE TITLE
python3.6 problems

### ISSUE THREAD

**Issue by ebylaska** [JannickWeisshaupt/OpenDFT#5]
It looks like pyside doesn't easily work with python3.6.  It looks like qt4 and pyside4 are being mothballed in favor of qt5 and pyside2.  This is causing problems for me on my mac laptop, which has python3.6.  I probably have an old linux box I can use for adding nwchem bindings.  However, my guess is that you'll need to convert to qt5 and pyside2 soon.  Unfortunately,  graphics libraries not being backward compatible has been a problem for a long time now (job security i guess for uncreative programmers).....Directly programming on the web may work better as one can always link in old libraries without having to install them on a machine....

**Comment by JannickWeisshaupt** [comment]
I included compatibility for pyqt4 as alternative.
