### ISSUE TITLE
Problem with QE DFT Engine -reg

### ISSUE THREAD

**Issue by mcvarma** [JannickWeisshaupt/OpenDFT#9]
Hi,
I tried to use OpenDFT to use with quantum espresso, but after selecting the path to the executibles, it is showing Engine Inactive and no calculation tab in DFT is showing up. Kindly provide me guidance in this regard.
Thank you
regards
M Chaitanya Varma
Associate Professor
Dept. of Physics
Institute of Science
GITAM University
India

**Comment by mcvarma** [comment]
This is what it is looking like. I even tried with abinit which is installed using sudo apt install, but still the same problem
![Screenshot from 2020-05-08 11-05-21](https://user-images.githubusercontent.com/65004615/81374070-fc399c80-911b-11ea-8747-d54dd998a3f9.png)
Kindly help me in this regard.
Thank you

**Comment by JannickWeisshaupt** [comment]
Thanks a lot for opening and issue. Could you gladly provide some information in order for me to reproduce the problem.

1. Could you type
pw.x 
into your terminal and provide me the output?
2. Could you got into the DFT engine tab in OpenDFT and select options. Then select in "engine at startup" the field ask at startup. Then restart OpenDFT and you should see an engine selection dialog. Installed engines are green and unavailable engines are red. Which ones are green and which are red in your case?
3. The state you see actually looks like you did not specify a structure yet. What do you see in the Structure tab? If it is empty you need to specify the structure first under File -> new Structure or File -> Import structure

**Comment by mcvarma** [comment]
Sir,
I tired all the options that you suggested but still the same problem persits.
Kindly help me in overcoming this problem. I am using UBUNTU18.04 os.
![Screenshot from 2020-05-13 20-26-08](https://user-images.githubusercontent.com/65004615/81829199-4675b000-9558-11ea-80a2-820240c520e9.png)

![Screenshot from 2020-05-13 20-25-55](https://user-images.githubusercontent.com/65004615/81829184-42e22900-9558-11ea-8526-c20fcb8f14af.png)

![Screenshot from 2020-05-13 20-25-43](https://user-images.githubusercontent.com/65004615/81829174-41186580-9558-11ea-956b-610ec3b2533f.png)
![Screenshot from 2020-05-13 20-24-13](https://user-images.githubusercontent.com/65004615/81829136-36f66700-9558-11ea-99c5-502564b93a21.png)
![Screenshot from 2020-05-13 20-24-30](https://user-images.githubusercontent.com/65004615/81829159-3cec4800-9558-11ea-86c2-5142aa0cb826.png)

**Comment by mcvarma** [comment]
Sir,
Issue is solved, first I started with New project and then created structure using cif file. Then everything is working as you showed in the site.
Thank you
regards
M Chaitanya Varma

**Comment by JannickWeisshaupt** [comment]
Glad I could help!
